### ISSUE TITLE
about shp. in  osmnx-street-compass 

### ISSUE THREAD

**Issue by lucascunha1979** [mradamcox/osmnx-street-compass#1]
hello Adam, how are you?

perfect your code to plot polar histograms from shapefiles ... I was trying to figure out how to do this for a long time

I am new to Python and would like to know exactly where I should insert my shp. in the code to get the histograms? would you have an example to show me?

grateful for the attention and congratulations for the code

Sincerely

Lucas

**Comment by mradamcox** [comment]
Hi Lucas @lucascunha1979, so sorry I am only seeing this now. To prepare your shapefile, make sure there is a `Name` field in it with a unique name for each feature. Then use the command in the README file, but substitute the path to your shapefile. For example, if your shapefile is named "my_shapefile.shp" this is the command you would use:

    python generate_street_orientations.py "full/system/path/to/my_shapefile.shp" -l Name -t "Title of your image"

Note, the shapefile is only used to define boundaries of road networks that are summarized in the historgrams. So it must be a polygon shapefile. This tool will not work to make a histogram out of a road network shapefile.
